# Generated by Django 5.2.7 on 2026-01-02 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=30, null=True)),
                ('Description', models.TextField(null=True)),
                ('Creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30, null=True)),
                ('Last_name', models.CharField(max_length=30, null=True)),
                ('Email', models.EmailField(max_length=254, null=True, unique=True)),
                ('Mobile_number', models.CharField(max_length=15, null=True)),
                ('Password', models.CharField(max_length=100, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Description', models.TextField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='item_images/')),
                ('Quantity', models.CharField(max_length=100, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocorder.category')),
            ],
        ),
    ]
