# Generated by Django 5.2.7 on 2026-01-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocorder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_name',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Description',
        ),
    ]
