# Generated by Django 5.2.7 on 2026-01-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocorder', '0002_rename_category_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
