# Generated by Django 5.2.7 on 2026-01-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocorder', '0003_rename_items_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Mobile_number',
            new_name='MobileNo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='First_name',
            new_name='first_name',
        ),
    ]
