# Generated by Django 5.2.7 on 2026-01-09 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocorder', '0004_rename_mobile_number_user_mobileno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_order_placed', models.BooleanField(default=False)),
                ('order_number', models.CharField(max_length=100)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocorder.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocorder.user')),
            ],
        ),
    ]
