# Generated by Django 5.2.7 on 2026-01-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocorder', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
