# Generated by Django 5.2.7 on 2026-01-21 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocorder', '0007_foodtracking_orderaddress_paymentdetails_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtracking',
            name='order_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grocorder.orderaddress'),
        ),
        migrations.AlterField(
            model_name='foodtracking',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grocorder.order'),
        ),
    ]
