# Generated by Django 5.2.7 on 2026-01-21 09:31

from django.db import migrations


def populate_order_address(apps, schema_editor):
    FoodTracking = apps.get_model('grocorder', 'FoodTracking')
    OrderAddress = apps.get_model('grocorder', 'OrderAddress')
    for tracking in FoodTracking.objects.filter(order_address__isnull=True, order__isnull=False):
        try:
            order_address = OrderAddress.objects.get(order_number=tracking.order.order_number)
            tracking.order_address = order_address
            tracking.save()
        except OrderAddress.DoesNotExist:
            pass  # Skip if no matching OrderAddress


class Migration(migrations.Migration):

    dependencies = [
        ('grocorder', '0008_foodtracking_order_address_alter_foodtracking_order'),
    ]

    operations = [
        migrations.RunPython(populate_order_address),
    ]
